
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
      secrets:
        - npm_token
    environment:
      - API_ENV=local
      - AWS_ACCESS_KEY_ID=${API_DEMO_AWS_ACCESS_KEY_ID:-}
      - AWS_SECRET_ACCESS_KEY=${API_DEMO_AWS_SECRET_ACCESS_KEY:-}
      - AWS_SESSION_TOKEN=${API_DEMO_AWS_SESSION_TOKEN:-}
      - DB_ENV
      - NODE_ENV=production
    ports:
      - '6662:8000'
    tty: true
    volumes:
      - ./src:/srv/api/src
      - ./pm2:/srv/api/pm2
      - ./package.json:/srv/api/package.json
      - ./tsconfig.json:/srv/api/tsconfig.json

secrets:
  npm_token:
    environment: NPM_TOKEN
