FROM node:24-alpine

RUN apk update && \
  apk add bash

ENV API_HOME="/srv/api"

ARG NPM_TOKEN

WORKDIR ${API_HOME}

RUN npm i pm2@6.0.14 -g

COPY package*.json ${API_HOME}/

COPY . ${API_HOME}/

RUN /bin/bash -c "test -f .build.npm-token.env && source .build.npm-token.env; npm i --include=dev;"  

RUN rm -f .npmrc

EXPOSE 8000

CMD ["pm2-runtime", "start", "pm2/process-local.json"]
