FROM node:20.12.1

ENV TERM xterm
ENV DEBIAN_FRONTEND noninteractive

# update index and install write/read data across TCP/UDP and python 3
RUN apt-get update -qy && apt-get install -qy \
  netcat-openbsd \
  python3-pip

WORKDIR /var/www

RUN python3 -m pip --no-cache-dir install --break-system-packages --upgrade awscli

# Install global node packages
RUN npm i -g npm@10.5.0
RUN npm i -g pm2@5.3

# set the loglevel for npm to remove red wall.
ENV NPM_CONFIG_LOGLEVEL=warn

# create npm_token variable to hold the private npm repo auth token
# token will be used at npm instsall
# used only by Travis.
ARG NPM_TOKEN

RUN mkdir /var/log/api

WORKDIR /var/www
RUN rm -rf *

COPY . .

# copy run.sh 
# if we attempt to run run.sh inside /var/www, it will error on permissions because Docker Compose uses maps volumes in real time.
COPY run.sh /run.sh

# EB env vars are only available at container run time.
# When deployed to EB, the test and source cmds will
# succeed due to 02-make-build-secrets.config .ebextension.
# The NPM_TOKEN should otherwise be defined for local and CI builds. ; 
RUN /bin/bash -c "test -f .build.npm-token.env && source .build.npm-token.env; npm i;"  

EXPOSE 8000

RUN chmod +x /run.sh
CMD ["/run.sh"]
