
services:
  api:
    build:
      context: .
      args:
        - NPM_TOKEN
      dockerfile: Dockerfile.local
    environment:
      - API_ENV=stage # <--change this to local eventually
      - AWS_ACCESS_KEY_ID=${API_DEMO_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${API_DEMO_AWS_SECRET_ACCESS_KEY}
      - DB_ENV
      - NODE_ENV=production
    ports:
      - '6662:8000'
    tty: true
    volumes:
      - .:/srv/api
      - node-modules:/srv/api/node_modules/
volumes:
  node-modules:
