/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticates a user with email and password
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description User email address
                         */
                        email: string;
                        /** @description User password */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        /** @description Sets access_token and refresh_token as HttpOnly cookies */
                        "set-cookie"?: string[];
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * Format: email
                             * @description User email address
                             * @example user@example.com
                             */
                            email: string;
                            /**
                             * @description User full name
                             * @example John Doe
                             */
                            full_name: string;
                            /**
                             * @description User known as name (usually first name)
                             * @example John
                             */
                            known_as: string | null;
                            /**
                             * @description Permission keys granted to the user (from the access token claim)
                             * @example [
                             *       "INTERNAL_USERS_READ",
                             *       "INTERNAL_USERS_WRITE"
                             *     ]
                             */
                            permissions: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User refresh tokens
         * @description Refreshes the access token and refresh tokens and issues new cookies using the existing refresh token cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Access token cookie refreshed */
                204: {
                    headers: {
                        /** @description Sets new access_token and refresh_token as HttpOnly cookies */
                        "set-cookie"?: string[];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Logs out user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User refresh token deleted from DB and both refresh and access cookies cleared */
                204: {
                    headers: {
                        /** @description Clears access_token and refresh_token HttpOnly cookies */
                        "set-cookie"?: string[];
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User password forgot
         * @description Triggers a password reset flow
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description User email address
                         */
                        email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User password reset
         * @description Resets a user's password using the token from the reset email
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Reset token from the password reset email link */
                        password_reset_token: string;
                        /** @description New password to set for the account */
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/password/reset/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a password reset token
         * @description Checks whether a password reset token is still valid (active user, unused and unexpired) without consuming it. Lets the front-end redirect a used or expired reset link before rendering the form.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Reset token from the password reset email link */
                        password_reset_token: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user
         * @description Returns the currently authenticated user, identified by the access_token cookie
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * Format: email
                             * @description User email address
                             * @example user@example.com
                             */
                            email: string;
                            /**
                             * @description User full name
                             * @example John Doe
                             */
                            full_name: string;
                            /**
                             * @description User known as name (usually first name)
                             * @example John
                             */
                            known_as: string | null;
                            /**
                             * @description Permission keys granted to the user (from the access token claim)
                             * @example [
                             *       "INTERNAL_USERS_READ",
                             *       "INTERNAL_USERS_WRITE"
                             *     ]
                             */
                            permissions: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one or more permissions
         * @description Returns one or more permissions
         */
        get: {
            parameters: {
                query?: {
                    /** @description Sort order */
                    order?: "ASC" | "DESC";
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Number of items per page (max 100, default 50) */
                    per_page?: string;
                    /** @description Search term to filter permissions by name or permission_id */
                    search?: string;
                    /** @description Field to sort by */
                    sort?: "name";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                permission_id: string;
                                name: string;
                                description: string;
                            }[];
                            pagination: {
                                page: number;
                                per_page: number;
                                pages: number;
                                count_page: number;
                                count_total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a permission
         * @description Create a permission
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Permission name, must be unique */
                        name: string;
                        /** @description Human readable description of the permission */
                        description: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Permission ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            permission_id: string;
                            /**
                             * @description Permission name
                             * @example INTERNAL_USERS_READ
                             */
                            name: string;
                            /**
                             * @description Human readable description of the permission
                             * @example Read users
                             */
                            description: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/permissions/{permission_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a permission
         * @description Update a permission
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Permission's id */
                    permission_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Permission name, must be unique */
                        name: string;
                        /** @description Human readable description of the permission */
                        description: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Permission ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            permission_id: string;
                            /**
                             * @description Permission name
                             * @example INTERNAL_USERS_READ
                             */
                            name: string;
                            /**
                             * @description Human readable description of the permission
                             * @example Read users
                             */
                            description: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a permission
         * @description Hard delete a permission
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Permission's id */
                    permission_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one or more roles
         * @description Returns one or more roles
         */
        get: {
            parameters: {
                query?: {
                    /** @description Sort order */
                    order?: "ASC" | "DESC";
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Number of items per page (max 100, default 50) */
                    per_page?: string;
                    /** @description Search term to filter roles by name or role_id */
                    search?: string;
                    /** @description Field to sort by */
                    sort?: "name";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                role_id: string;
                                name: string;
                                description: string;
                            }[];
                            pagination: {
                                page: number;
                                per_page: number;
                                pages: number;
                                count_page: number;
                                count_total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a role
         * @description Create a role
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Role name, must be unique */
                        name: string;
                        /** @description Human readable description of the role */
                        description: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Role ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            role_id: string;
                            /**
                             * @description Role name
                             * @example ADMIN
                             */
                            name: string;
                            /**
                             * @description Human readable description of the role
                             * @example Full access to all resources
                             */
                            description: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a role
         * @description Update a role
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role's id */
                    role_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Role name, must be unique */
                        name: string;
                        /** @description Human readable description of the role */
                        description: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Role ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            role_id: string;
                            /**
                             * @description Role name
                             * @example ADMIN
                             */
                            name: string;
                            /**
                             * @description Human readable description of the role
                             * @example Full access to all resources
                             */
                            description: string;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a role
         * @description Hard delete a role
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role's id */
                    role_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get roles with their assigned permissions
         * @description Returns roles with their assigned permissions. Pass an optional "role_id" query parameter to return a single role.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional role id to return a single role */
                    role_id?: string;
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Number of items per page (max 100, default 50) */
                    per_page?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                role_id: string;
                                role_name: string;
                                permissions: {
                                    [key: string]: {
                                        /** Format: uuid */
                                        permission_id: string;
                                        permission_name: string;
                                    };
                                };
                            }[];
                            pagination: {
                                page: number;
                                per_page: number;
                                pages: number;
                                count_page: number;
                                count_total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/{role_id}/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a role's permissions
         * @description Replaces the role's entire permission set with the supplied permissions.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role's id */
                    role_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The complete set of permission ids the role should have */
                        permissions: string[];
                    };
                };
            };
            responses: {
                /** @description The modified role-permission resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Role ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            role_id: string;
                            /**
                             * @description Permission ids now assigned to the role
                             * @example [
                             *       "a3bb189e-8bf9-3888-9912-ace4e6543002",
                             *       "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                             *     ]
                             */
                            permissions: string[];
                        };
                    };
                };
            };
        };
        /**
         * Assign a role's initial permissions
         * @description Assigns one or more permissions to a role that currently has none, returning the created role-permission resource. Fails if the role already has any permissions — use PUT to replace an existing permission set, or DELETE followed by POST to reset it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role's id */
                    role_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Permission ids to assign to the role */
                        permissions: string[];
                    };
                };
            };
            responses: {
                /** @description The created role-permission resource */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description Role ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            role_id: string;
                            /**
                             * @description Permission ids assigned to the role
                             * @example [
                             *       "a3bb189e-8bf9-3888-9912-ace4e6543002",
                             *       "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                             *     ]
                             */
                            permissions: string[];
                        };
                    };
                };
            };
        };
        /**
         * Remove all of a role's permissions
         * @description Removes every permission assigned to the role.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Role's id */
                    role_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health_db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database health check endpoint
         * @description Returns the current health status of the database server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Health status indicator
                             * @enum {string}
                             */
                            status: "OK";
                            /**
                             * Format: date-time
                             * @description ISO timestamp of the health check
                             */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health_eb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Elastic Beanstalk health check endpoint
         * @description Returns the current health status of the API service for Elastic Beanstalk
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Health status indicator
                             * @enum {string}
                             */
                            status: "OK";
                            /**
                             * Format: date-time
                             * @description ISO timestamp of the health check
                             */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal-users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one or more users
         * @description Returns one or more users
         */
        get: {
            parameters: {
                query?: {
                    /** @description Sort order */
                    order?: "ASC" | "DESC";
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Number of items per page (max 100, default 50) */
                    per_page?: string;
                    /** @description Filter by status */
                    status?: ("CREATED" | "INVITED" | "ACTIVE" | "DEACTIVATED") | ("CREATED" | "INVITED" | "ACTIVE" | "DEACTIVATED")[];
                    /** @description Search term to filter users by name (any part of full name), email or user_id */
                    search?: string;
                    /** @description Field to sort by */
                    sort?: "name" | "email" | "created_at";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                user_id: string;
                                /** Format: email */
                                email: string;
                                full_name: string;
                                known_as: string | null;
                                status: string;
                            }[];
                            pagination: {
                                page: number;
                                per_page: number;
                                pages: number;
                                count_page: number;
                                count_total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a user
         * @description Create a user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description User's email address, must be unique
                         */
                        email: string;
                        /** @description User's full name */
                        full_name: string;
                        /** @description User's known by name */
                        known_as?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * Format: email
                             * @description User email address
                             * @example john.doe@example.com
                             */
                            email: string;
                            /**
                             * @description User full name
                             * @example John Doe
                             */
                            full_name: string;
                            /**
                             * @description User known as name (usually first name)
                             * @example John
                             */
                            known_as: string | null;
                            /**
                             * @description The status of the user, this will be CREATED for new users
                             * @example CREATED
                             */
                            status: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal-users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a user
         * @description Update a user
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description User's full name */
                        full_name: string;
                        /** @description User's known by name */
                        known_as?: string | null;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description User full name
                             * @example John Doe
                             */
                            full_name: string;
                            /**
                             * @description User known as name (usually first name)
                             * @example John
                             */
                            known_as: string | null;
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete a user
         * @description Hard delete a user; only with a status of CREATED
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal-users/{user_id}/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a user's email
         * @description Change a user's email
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description New user's email address, must be unique
                         */
                        new_email: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * Format: email
                             * @description User new email
                             * @example john.doe@email.com
                             */
                            email: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/internal-users/{user_id}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel a user invitation
         * @description Cancels a pending invitation; only with a status of INVITED. Reverts the user to CREATED and clears the invitation token, expiry and email-sent stamp.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User's id
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description User's changed status: 'CREATED'
                             * @example CREATED
                             */
                            status: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Invite a user
         * @description Invites a user; only with a status of CREATED, INVITED (for re-invite) or DEACTIVATED (for re-activation)
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User's id
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description User's changed status: 'INVITED'
                             * @example INVITED
                             */
                            status: string;
                            /**
                             * @description The sent status of the invite email
                             * @example true
                             */
                            invite_email_sent: boolean;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/internal-users/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate an invited user
         * @description Activates an invited user using the token from the activation email and sets the account password
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Invitation token from the activation email link */
                        token: string;
                        /** @description Password to set for the account */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal-users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Deactivate a user
         * @description Deactivates a user; only with a status of ACTIVE
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User's id
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description User's changed status: 'DEACTIVATED'
                             * @example DEACTIVATED
                             */
                            status: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/internal-users/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get users with their assigned roles
         * @description Returns users with their assigned roles. Pass an optional "user_id" query parameter to return a single user.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional user id to return a single user */
                    user_id?: string;
                    /** @description Page number (default 1) */
                    page?: string;
                    /** @description Number of items per page (max 100, default 50) */
                    per_page?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                user_id: string;
                                /** Format: email */
                                user_email: string;
                                user_full_name: string;
                                roles: {
                                    [key: string]: {
                                        /** Format: uuid */
                                        role_id: string;
                                        role_name: string;
                                    };
                                };
                            }[];
                            pagination: {
                                page: number;
                                per_page: number;
                                pages: number;
                                count_page: number;
                                count_total: number;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal-users/{user_id}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a user's roles
         * @description Replaces the user's entire role set with the supplied roles. An empty array clears all of the user's roles.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description The complete set of role ids the user should have. Pass an empty array to remove all roles. */
                        roles: string[];
                    };
                };
            };
            responses: {
                /** @description The modified user-role resource */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description Role ids now assigned to the user
                             * @example [
                             *       "a3bb189e-8bf9-3888-9912-ace4e6543002",
                             *       "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                             *     ]
                             */
                            roles: string[];
                        };
                    };
                };
            };
        };
        /**
         * Assign a user's initial roles
         * @description Assigns one or more roles to a user that currently has none, returning the created user-role resource. Fails if the user already has any roles — use PUT to replace an existing role set, or DELETE followed by POST to reset it.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Role ids to assign to the user */
                        roles: string[];
                    };
                };
            };
            responses: {
                /** @description The created user-role resource */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: uuid
                             * @description User ID
                             * @example 7acd58cc-4ae5-4046-9037-383a057e4970
                             */
                            user_id: string;
                            /**
                             * @description Role ids assigned to the user
                             * @example [
                             *       "a3bb189e-8bf9-3888-9912-ace4e6543002",
                             *       "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                             *     ]
                             */
                            roles: string[];
                        };
                    };
                };
            };
        };
        /**
         * Remove all of a user's roles
         * @description Removes every role assigned to the user.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description User's id */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
