/* @name RolesGetRoles */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_roles AS (
	SELECT
	  r.id AS role_id
	  , r.name
	  , r.description
		, COUNT(*) OVER () AS total
	FROM
	  internal.roles AS r
	WHERE
		COALESCE(
			r.name ILIKE :search
			OR r.id::text ILIKE :search
		, TRUE)
	ORDER BY
		-- Direction can't be parameterized, so each direction is a separate gated term.
		CASE WHEN :order! = 'DESC' THEN
			CASE :sort!
				WHEN 'name' THEN r.name
			END
		END DESC
		, CASE WHEN :order = 'ASC' THEN
			CASE :sort
				WHEN 'name' THEN r.name
			END
		END ASC
		, r.id ASC
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	json_object_agg(
		tr.role_id
		,json_build_object(
			'name', tr.name
			, 'description', tr.description
		)
	) AS roles
	, COALESCE(MAX(tr.total), 0)::int AS total
FROM
	t_roles AS tr
;
