/* @name RolesGetRoles */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_roles AS (
	SELECT
		r.id AS role_id
		, r.name
		, r.description
	FROM
		internal.roles AS r
	WHERE
		COALESCE(
			r.name ILIKE :search
			OR r.id::text ILIKE :search
		, TRUE)
),
t_page AS (
	SELECT
		rg.*
		, ROW_NUMBER() OVER () AS ord
	FROM (
		SELECT
			*
		FROM
			t_roles
		ORDER BY
			-- Direction can't be parameterized, so each direction is a separate gated term.
			CASE WHEN :order! = 'DESC' THEN
				CASE :sort!
					WHEN 'name' THEN name
				END
			END DESC
			, CASE WHEN :order = 'ASC' THEN
				CASE :sort
					WHEN 'name' THEN name
				END
			END ASC
			, role_id ASC
		LIMIT
			:limit!
		OFFSET
			:offset!
	) AS rg
)
SELECT
	COALESCE(
		json_agg(
			json_build_object(
				'role_id', tp.role_id
				, 'name', tp.name
				, 'description', tp.description
			)
			ORDER BY tp.ord
		)
	, '[]'::json) AS roles
	, COALESCE((SELECT COUNT(*) FROM t_roles), 0)::int AS total
FROM
	t_page AS tp
;
