import fs from 'fs/promises';
import path from 'path';

const ROOT = process.cwd();
const ROUTES_DIR = path.join(ROOT, 'src', 'routes');

function toPosix(inputPath: string): string {
  return inputPath.split(path.sep).join('/');
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function queryNameFromSqlPath(sqlPath: string): string {
  const relative = path.relative(ROUTES_DIR, sqlPath);
  const withoutExt = relative.replace(/\.sql$/i, '');

  return toPascalCase(withoutExt);
}

function toTypedSql(sql: string, queryName: string): string {
  const converted = sql.replace(/\$([a-zA-Z][a-zA-Z0-9_]*)\b/g, ':$1');

  return [
    `/* @name ${queryName} */`,
    '/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */',
    converted.trim(),
    '',
  ].join('\n');
}

function shouldGenerate(sql: string): boolean {
  if (/<%=/.test(sql)) return false;

  // Limit generation to read queries where return types are useful and stable.
  const hasReadQuery = /\b(SELECT|WITH)\b/i.test(sql);

  if (!hasReadQuery) return false;

  return true;
}

async function walk(dirPath: string): Promise<string[]> {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const absolutePath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      const nested = await walk(absolutePath);
      results.push(...nested);
      continue;
    }

    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.sql')) continue;
    if (entry.name.endsWith('.typed.sql')) continue;

    results.push(absolutePath);
  }

  return results;
}

async function ensureDir(filePath: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

async function main(): Promise<void> {
  const sourceSqlFiles = await walk(ROUTES_DIR);
  const generatedSet = new Set<string>();

  for (const sourceFile of sourceSqlFiles) {
    const sql = await fs.readFile(sourceFile, 'utf8');

    if (!shouldGenerate(sql)) continue;

    const queryName = queryNameFromSqlPath(sourceFile);
    const typedSql = toTypedSql(sql, queryName);
    const sourceDir = path.dirname(sourceFile);
    const fileName = path.basename(sourceFile);
    const typedFile = path.join(sourceDir, 'types', fileName.replace(/\.sql$/i, '.typed.sql'));

    generatedSet.add(typedFile);
    await ensureDir(typedFile);
    await fs.writeFile(typedFile, typedSql, 'utf8');
  }

  // Gather all existing .typed.sql files from types directories
  async function walkTypedSql(dirPath: string): Promise<string[]> {
    const entries = await fs.readdir(dirPath, { withFileTypes: true });
    const results: string[] = [];

    for (const entry of entries) {
      const absolutePath = path.join(dirPath, entry.name);

      if (entry.isDirectory()) {
        results.push(...await walkTypedSql(absolutePath));
        continue;
      }

      if (!entry.isFile()) continue;
      if (!entry.name.endsWith('.typed.sql')) continue;

      results.push(absolutePath);
    }

    return results;
  }

  const existingTypedSql = await walkTypedSql(ROUTES_DIR);

  // Remove stale generated files so source .sql remains the single source of truth.
  for (const typedFile of existingTypedSql) {
    if (generatedSet.has(typedFile)) continue;

    const blob = await fs.readFile(typedFile, 'utf8');

    if (!blob.includes('AUTO-GENERATED FROM SOURCE .sql')) continue;

    await fs.rm(typedFile, { force: true });
  }

  const generatedList = [...generatedSet]
    .map((item) => toPosix(path.relative(ROOT, item)))
    .sort();

  console.log(`Generated ${generatedList.length} typed SQL file(s).`);
  for (const item of generatedList) console.log(item);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
