/* @name InternalUsersGetNonDeactivatedUserById */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
	u.id AS user_id
FROM
	internal.users AS u
WHERE
	u.id = :userId!
	AND u.status <> 'DEACTIVATED'
;
