/* @name InternalUsersRemoveUser */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
DELETE FROM
  internal.users
WHERE
  id = :userId!
  AND status = 'CREATED'
RETURNING
  id AS user_id
;
