/* @name InternalUsersSetUserEmail */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  internal.users
SET
  email = :newEmail!
WHERE
  id = :userId!
RETURNING
  id AS user_id
  , email
;
