/* @name UsersAddUser */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
INSERT INTO public.users
	(
		email
		, full_name
		, known_as
	)
VALUES
	(
		:email
		, :fullName
		, :knownAs
	)
RETURNING
	id
	, email
	, full_name
	, known_as
	, status
;
