/* @name UsersGetUsers */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_users AS (
	SELECT
	  u.id
	  , u.email
	  , u.full_name
	  , u.known_as
		, u.is_active
	FROM
	  public.users AS u
	WHERE
		COALESCE((u.is_active = :isActive), TRUE)
	  AND COALESCE((u.id = :userId), TRUE)
	ORDER BY
		split_part(u.full_name, ' ', -1) ASC
		, u.id ASC
	LIMIT
		:limit
	OFFSET
		:offset
)
SELECT
	json_object_agg(
		tu.id
		,json_build_object(
			'email', tu.email
			, 'full_name', tu.full_name
			, 'known_as', tu.known_as
			, 'is_active', tu.is_active
		)
	) AS users
FROM
	t_users AS tu
;
