/* @name UsersGetUsers */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_users AS (
	SELECT
	  u.id AS user_id
	  , u.email
	  , u.full_name
	  , u.known_as
		, u.status
		, COUNT(*) OVER () AS total
	FROM
	  internal.users AS u
	WHERE
		COALESCE(u.status = ANY(:status), TRUE)
	  AND COALESCE(
			u.full_name ILIKE :search
			OR u.email ILIKE :search
			OR u.id::text ILIKE :search
		, TRUE)
	ORDER BY
		-- Direction can't be parameterized, so each direction is a separate gated
		-- term. created_at is rendered as fixed-width text (zero-padded, 6-digit
		-- microseconds) so it shares the text CASE and still sorts chronologically.
		CASE WHEN :order! = 'DESC' THEN
			CASE :sort!
				WHEN 'name' THEN split_part(u.full_name, ' ', -1)
				WHEN 'email' THEN u.email
				WHEN 'created_at' THEN to_char(u.created_at, 'YYYY-MM-DD HH24:MI:SS.US')
			END
		END DESC
		, CASE WHEN :order = 'ASC' THEN
			CASE :sort
				WHEN 'name' THEN split_part(u.full_name, ' ', -1)
				WHEN 'email' THEN u.email
				WHEN 'created_at' THEN to_char(u.created_at, 'YYYY-MM-DD HH24:MI:SS.US')
			END
		END ASC
		, u.id ASC
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	json_object_agg(
		tu.user_id
		,json_build_object(
			'email', tu.email
			, 'full_name', tu.full_name
			, 'known_as', tu.known_as
			, 'status', tu.status
		)
	) AS users
	, COALESCE(MAX(tu.total), 0)::int AS total
FROM
	t_users AS tu
;
