/* @name UsersGetUsers */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_users AS (
	SELECT
	  u.id
	  , u.email
	  , u.full_name
	  , u.known_as
	FROM
	  public.users AS u
	WHERE
	  u.is_active = TRUE
	  AND COALESCE((u.id = :userId), TRUE)
)
SELECT
	json_object_agg(
		tu.id
		,json_build_object(
			'email', tu.email
			, 'full_name', tu.full_name
			, 'known_as', tu.known_as 
		)
	) AS users
FROM 
	t_users AS tu
;
