/* @name UsersGetUserByStatus */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
  u.id AS user_id
FROM
  public.users AS u
WHERE
  u.id = :userId!
  AND u.status = ANY(:status!)
;
