/* @name UsersSetUserDeactivated */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  public.users
SET
  deactivated_at = NOW()
  , password_hash = :newPasswordHash!
  , token_refresh_hash = NULL
WHERE
  id = :userId!
  AND status = 'ACTIVE'
RETURNING
  id
;
