/* @name UsersSetUserActive */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_activated AS (
  UPDATE
    public.users AS u
  SET
    activated_at = NOW()
  FROM
    public.users_authentication AS ua
  WHERE
    u.id = ua.user_id
    AND ua.invite_token_hash = :inviteTokenHash!
    AND ua.invite_token_expiry_at > NOW()
    AND u.status = 'INVITED'
  RETURNING
    u.id
    , u.status
)
UPDATE
  public.users_authentication AS a
SET
  password_hash = :passwordHash!
  , invite_token_hash = NULL
  , invite_token_expiry_at = NULL
FROM
  t_activated
WHERE
  a.user_id = t_activated.id
RETURNING
  a.user_id
  , t_activated.status AS status
;
