/* @name UsersSetUser */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  public.users
SET
  full_name = :fullName!
  , known_as = :knownAs
WHERE
  id = :userId!
RETURNING
  id AS user_id
  , full_name
  , known_as
;
