/* @name UsersSetUserInvited */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_invited AS (
  UPDATE
    public.users
  SET
    invited_at = NOW()
    , deactivated_at = NULL
    , activated_at = NULL
  WHERE
    id = :userId!
    AND status = ANY('{CREATED, INVITED, DEACTIVATED}')
  RETURNING
    id
    , email
    , status
)
UPDATE
  public.users_authentication AS a
SET
  invite_token_hash = :inviteTokenHash!
  , invite_token_expiry_at = NOW() + make_interval(days => :inviteTokenExpiryDays!)
  , invite_email_sent_at = NULL
FROM
  t_invited AS i
WHERE
  a.user_id = i.id
RETURNING
  i.id AS user_id
  , i.email
  , i.status
;
