/* @name PermissionsAddPermission */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
INSERT INTO internal.permissions
	(
		name
		, description
	)
VALUES
	(
		:name!
		, :description
	)
RETURNING
	id AS permission_id
	, name
	, description
;
