/* @name PermissionsGetPermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_permissions AS (
	SELECT
	  p.id AS permission_id
	  , p.name
	  , p.description
		, COUNT(*) OVER () AS total
	FROM
	  internal.permissions AS p
	WHERE
	  COALESCE((p.id = :permissionId), TRUE)
	ORDER BY
		p.name ASC
		, p.id ASC
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	json_object_agg(
		tp.permission_id
		,json_build_object(
			'name', tp.name
			, 'description', tp.description
		)
	) AS permissions
	, COALESCE(MAX(tp.total), 0)::int AS total
FROM
	t_permissions AS tp
;
