/* @name PermissionsGetPermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_permissions AS (
	SELECT
		p.id AS permission_id
		, p.name
		, p.description
	FROM
		internal.permissions AS p
	WHERE
		COALESCE(
			p.name ILIKE :search
			OR p.id::text ILIKE :search
		, TRUE)
),
t_page AS (
	SELECT
		pg.*
		, ROW_NUMBER() OVER () AS ord
	FROM (
		SELECT
			*
		FROM
			t_permissions
		ORDER BY
			-- Direction can't be parameterized, so each direction is a separate gated term.
			CASE WHEN :order! = 'DESC' THEN
				CASE :sort!
					WHEN 'name' THEN name
				END
			END DESC
			, CASE WHEN :order = 'ASC' THEN
				CASE :sort
					WHEN 'name' THEN name
				END
			END ASC
			, permission_id ASC
		LIMIT
			:limit!
		OFFSET
			:offset!
	) AS pg
)
SELECT
	COALESCE(
		json_agg(
			json_build_object(
				'permission_id', tp.permission_id
				, 'name', tp.name
				, 'description', tp.description
			)
			ORDER BY tp.ord
		)
	, '[]'::json) AS permissions
	, COALESCE((SELECT COUNT(*) FROM t_permissions), 0)::int AS total
FROM
	t_page AS tp
;
