/* @name PermissionsSetPermission */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  internal.permissions
SET
  name = :name!
  , description = :description!
WHERE
  id = :permissionId!
RETURNING
  id AS permission_id
  , name
  , description
;
