/* @name RolesPermissionsAddRolePermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
INSERT INTO internal.roles_permissions
	(
		role_id
		, permission_id
	)
SELECT
	:roleId!
	, p.id
FROM
	internal.permissions AS p
WHERE
	p.id = ANY(:permissionIds!)
RETURNING
	permission_id
;
