/* @name RolesPermissionsGetRolesPermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_roles AS (
	SELECT
		r.id AS role_id
		, r.name AS role_name
	FROM
		internal.roles AS r
	WHERE
		COALESCE((r.id = :roleId), TRUE)
),
t_ranked AS (
	-- Rank the filtered set once by the requested sort. The page (t_page) and the JSON
	-- array below both order by this rank, so the result order is deterministic —
	-- ROW_NUMBER's ORDER BY and json_agg's ORDER BY are both guaranteed by SQL.
	SELECT
		*
		, ROW_NUMBER() OVER (
			ORDER BY
				role_name ASC
				, role_id ASC
		) AS ord
	FROM
		t_roles
),
t_page AS (
	SELECT
		*
	FROM
		t_ranked
	ORDER BY
		ord
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	COALESCE(
		json_agg(
			json_build_object(
				'role_id', tp.role_id
				, 'role_name', tp.role_name
				, 'permissions', COALESCE(rp.permissions, '{}'::json)
			)
			ORDER BY tp.ord
		)
	, '[]'::json) AS roles
	, COALESCE((SELECT COUNT(*) FROM t_roles), 0)::int AS total
FROM
	t_page AS tp
	LEFT JOIN LATERAL (
		SELECT
			json_object_agg(
				p.id
				, json_build_object(
					'permission_id', p.id
					, 'permission_name', p.name
				)
				ORDER BY
					p.name ASC
			) AS permissions
		FROM
			internal.roles_permissions AS rp
			INNER JOIN internal.permissions AS p ON p.id = rp.permission_id
		WHERE
			rp.role_id = tp.role_id
	) AS rp ON TRUE
;
