/* @name RolesPermissionsGetRolesPermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_roles AS (
	SELECT
		r.id AS role_id
		, r.name AS role_name
	FROM
		internal.roles AS r
	WHERE
		COALESCE((r.id = :roleId), TRUE)
),
t_page AS (
	SELECT
		rg.*
		, ROW_NUMBER() OVER () AS ord
	FROM (
		SELECT
			*
		FROM
			t_roles
		ORDER BY
			role_name ASC
			, role_id ASC
		LIMIT
			:limit!
		OFFSET
			:offset!
	) AS rg
)
SELECT
	COALESCE(
		json_agg(
			json_build_object(
				'role_id', tp.role_id
				, 'role_name', tp.role_name
				, 'permissions', COALESCE(rp.permissions, '{}'::json)
			)
			ORDER BY tp.ord
		)
	, '[]'::json) AS roles
	, COALESCE((SELECT COUNT(*) FROM t_roles), 0)::int AS total
FROM
	t_page AS tp
	LEFT JOIN LATERAL (
		SELECT
			json_object_agg(
				p.id
				, json_build_object(
					'permission_id', p.id
					, 'permission_name', p.name
				)
				ORDER BY
					p.name ASC
			) AS permissions
		FROM
			internal.roles_permissions AS rp
			INNER JOIN internal.permissions AS p ON p.id = rp.permission_id
		WHERE
			rp.role_id = tp.role_id
	) AS rp ON TRUE
;
