/* @name RolesPermissionsGetRolesPermissions */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_roles AS (
	SELECT
	  r.id AS role_id
	  , r.name AS role_name
		, COUNT(*) OVER () AS total
	FROM
	  internal.roles AS r
	WHERE
	  COALESCE((r.id = :roleId), TRUE)
	ORDER BY
		r.name ASC
		, r.id ASC
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	json_object_agg(
		tr.role_id
		, json_build_object(
			'role_id', tr.role_id
			, 'role_name', tr.role_name
			, 'permissions', COALESCE(rp.permissions, '{}'::json)
		)
	) AS roles
	, COALESCE(MAX(tr.total), 0)::int AS total
FROM
	t_roles AS tr
	LEFT JOIN LATERAL (
		SELECT
			json_object_agg(
				p.id
				, json_build_object(
					'permission_id', p.id
					, 'permission_name', p.name
				)
			) AS permissions
		FROM
			internal.roles_permissions AS rp
			INNER JOIN internal.permissions AS p ON p.id = rp.permission_id
		WHERE
			rp.role_id = tr.role_id
	) AS rp ON TRUE
;
