import fs from 'fs/promises';
import path from 'path';

import type { Manifest } from './shared.ts';
import { MANIFEST_PATH, ROOT, SOURCE_DIRS, shouldGenerate, walk } from './shared.ts';

function toPosix(inputPath: string): string {
  return inputPath.split(path.sep).join('/');
}

function toPascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function queryNameFromSqlPath(sqlPath: string, sourceDir: string): string {
  const relative = path.relative(sourceDir, sqlPath);
  const withoutExt = relative.replace(/\.sql$/i, '');

  return toPascalCase(withoutExt);
}

function toTypedSql(sql: string, queryName: string): string {
  const converted = sql.replace(/\$([a-zA-Z][a-zA-Z0-9_]*)\b/g, ':$1');

  return [
    `/* @name ${queryName} */`,
    '/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */',
    converted.trim(),
    '',
  ].join('\n');
}

async function walkTypedSql(dirPath: string): Promise<string[]> {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });
  const results: string[] = [];

  for (const entry of entries) {
    const absolutePath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      results.push(...await walkTypedSql(absolutePath));
      continue;
    }

    if (!entry.isFile()) continue;
    if (!entry.name.endsWith('.typed.sql')) continue;

    results.push(absolutePath);
  }

  return results;
}

async function ensureDir(filePath: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
}

/** Extracts exported identifier names from a .typed.queries.ts file. */
async function readExports(queriesPath: string): Promise<string[]> {
  const content = await fs.readFile(queriesPath, 'utf8').catch(() => '');
  if (!content) return [];
  const regex = /^export\s+(?:interface|const|type)\s+([A-Za-z_][A-Za-z0-9_]*)/gm;
  const names: string[] = [];
  let m;
  while ((m = regex.exec(content)) !== null) names.push(m[1]);
  return names;
}

async function processDir(sourceDir: string, generatedSet: Set<string>, manifest: Manifest): Promise<void> {
  const dirExists = await fs.access(sourceDir).then(() => true).catch(() => false);

  if (!dirExists) return;

  const sourceSqlFiles = await walk(sourceDir);

  for (const sourceFile of sourceSqlFiles) {
    const sql = await fs.readFile(sourceFile, 'utf8');

    if (!shouldGenerate(sql)) continue;

    const queryName = queryNameFromSqlPath(sourceFile, sourceDir);
    const typedSql = toTypedSql(sql, queryName);
    const fileDir = path.dirname(sourceFile);
    const fileName = path.basename(sourceFile);
    const typedFile = path.join(fileDir, 'types', fileName.replace(/\.sql$/i, '.typed.sql'));

    const typedQueriesPath = typedFile.replace(/\.typed\.sql$/i, '.typed.queries.ts');
    const isNew = !(await fs.access(typedQueriesPath).then(() => true).catch(() => false));

    generatedSet.add(typedFile);

    if (isNew) {
      manifest.created.push({
        typedSqlPath: typedFile,
        typedQueriesPath,
        queryName,
        exports: [],
      });
    }

    await ensureDir(typedFile);
    const existing = await fs.readFile(typedFile, 'utf8').catch(() => '');
    if (existing !== typedSql) {
      await fs.writeFile(typedFile, typedSql, 'utf8');
    }
  }

  // Remove stale generated files so source .sql remains the single source of truth.
  const existingTypedSql = await walkTypedSql(sourceDir);

  for (const typedFile of existingTypedSql) {
    if (generatedSet.has(typedFile)) continue;

    const blob = await fs.readFile(typedFile, 'utf8');

    if (!blob.includes('AUTO-GENERATED FROM SOURCE .sql')) continue;

    // Extract the query name from the @name marker before deleting.
    const nameMatch = blob.match(/\/\* @name (\w+) \*\//);
    const queryName = nameMatch?.[1] ?? '';

    const typedQueriesPath = typedFile.replace(/\.typed\.sql$/i, '.typed.queries.ts');
    const exports = await readExports(typedQueriesPath);

    manifest.deleted.push({
      typedSqlPath: typedFile,
      typedQueriesPath,
      queryName,
      exports,
    });

    await fs.rm(typedFile, { force: true });
    await fs.rm(typedQueriesPath, { force: true });
  }
}

async function main(): Promise<void> {
  const generatedSet = new Set<string>();
  const manifest: Manifest = {
    deleted: [],
    created: [],
  };

  for (const sourceDir of SOURCE_DIRS) {
    await processDir(sourceDir, generatedSet, manifest);
  }

  if (manifest.deleted.length > 0 || manifest.created.length > 0) {
    await fs.writeFile(MANIFEST_PATH, JSON.stringify(manifest, null, 2), 'utf8');
  }

  const generatedList = [...generatedSet]
    .map((item) => toPosix(path.relative(ROOT, item)))
    .sort();

  console.log(`Tracking ${generatedList.length} typed SQL file(s).`);
  for (const item of generatedList) console.log(item);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
