/* @name AuthGetUserByPasswordResetToken */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
  ua.user_id
FROM
  internal.users_authentication AS ua
  INNER JOIN internal.users AS u ON u.id = ua.user_id
WHERE
  ua.password_reset_token_hash = :passwordResetTokenHash!
  AND ua.password_reset_token_expiry_at > NOW()
  AND u.status = 'ACTIVE'
;
