/* @name AuthGetUserByEmail */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
  u.id AS user_id
  , u.email
  , u.full_name
  , u.known_as
  , a.password_hash
FROM
  internal.users AS u
  INNER JOIN internal.users_authentication AS a ON a.user_id = u.id
WHERE
  u.email = :email!
  AND u.status = 'ACTIVE'
;
