/* @name AuthGetUserByEmail */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
  u.id
  , u.email
  , u.full_name
  , u.known_as
  , u.password_hash
FROM
  public.users AS u
WHERE
  u.email = :email
  and u.is_active = true
;
