/* @name AuthSetUserRefreshHashOnRefresh */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  public.users
SET
  token_refresh_hash = :newTokenRefreshHash
WHERE
  id = :userId
  AND status = 'ACTIVE'
RETURNING
  id
;
