/* @name AuthSetUserRefreshHashNull */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
UPDATE
  public.users
SET
  token_refresh_hash = NULL
WHERE
  id = :userId
  AND token_refresh_hash IS NOT NULL
RETURNING
  id
;
