/* @name AuthenticationGetUserByEmail */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
SELECT
  u.id AS user_id
  , u.email
  , u.full_name
  , u.known_as
  , a.password_hash
  , COALESCE(ARRAY_AGG(DISTINCT p.name) FILTER (WHERE p.name IS NOT NULL), '{}'::varchar[]) AS permissions
FROM
  internal.users AS u
  INNER JOIN internal.users_authentication AS a ON a.user_id = u.id
  LEFT JOIN internal.users_roles AS ur ON ur.user_id = u.id
  LEFT JOIN internal.roles AS r ON r.id = ur.role_id
  LEFT JOIN internal.roles_permissions AS rp ON rp.role_id = r.id
  LEFT JOIN internal.permissions AS p ON p.id = rp.permission_id
WHERE
  u.email = :email!
  AND u.status = 'ACTIVE'
GROUP BY
 	u.id
  , u.email
  , u.full_name
  , u.known_as
  , a.password_hash
;
