/* @name UsersRolesGetUsersRoles */
/* AUTO-GENERATED FROM SOURCE .sql. DO NOT EDIT THIS FILE. */
WITH t_users AS (
	SELECT
	  u.id AS user_id
	  , u.email AS user_email
		, COUNT(*) OVER () AS total
	FROM
	  internal.users AS u
	WHERE
	  COALESCE((u.id = :userId), TRUE)
	ORDER BY
		u.email ASC
		, u.id ASC
	LIMIT
		:limit!
	OFFSET
		:offset!
)
SELECT
	json_object_agg(
		tu.user_id
		, json_build_object(
			'user_id', tu.user_id
			, 'user_email', tu.user_email
			, 'roles', COALESCE(ur.roles, '{}'::json)
		)
	) AS users
	, COALESCE(MAX(tu.total), 0)::int AS total
FROM
	t_users AS tu
	LEFT JOIN LATERAL (
		SELECT
			json_object_agg(
				r.id
				, json_build_object(
					'role_id', r.id
					, 'role_name', r.name
				)
			) AS roles
		FROM
			internal.users_roles AS ur
			INNER JOIN internal.roles AS r ON r.id = ur.role_id
		WHERE
			ur.user_id = tu.user_id
	) AS ur ON TRUE
;
